/*

 C01.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char C01[] =
{
  0x00,0x3F,0x00,0x7F,0x01,0xF1,0x05,0xE5,
  0x01,0xC1,0x03,0xC3,0x0E,0xCE,0x38,0xF8,
  0x00,0xFC,0x00,0xFE,0x80,0x8F,0xA0,0xA7,
  0x80,0x83,0xC0,0xC3,0x70,0x73,0x1C,0x1F
};

/* End of C01.C */
