/*

 MAP1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 43 x 18
   Tile set      : D:\下載\GB開發-20210501T140457Z-001\GB開發\TILE DESIGINER\Tiles\233.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MAP1Width 43
#define MAP1Height 18
#define MAP1Bank 0

extern unsigned char MAP1[];

/* End of MAP1.H */
